import prisma from "@/libs/prismadb";
import { LegalReminderType, LegalReminderPriority } from "@prisma/client";

/**
 * Gere les rappels admin (sans userId) pour la mise a jour des donnees.
 *
 * Deux rappels annuels :
 * - ANIL_DATA_UPDATE : 1er octobre → verifier si l'ANIL a publie les nouvelles donnees (due 15 oct)
 * - RENT_CONTROL_DATA_UPDATE : 1er juillet → mettre a jour les arretes d'encadrement (due 15 juil)
 */
export class AdminReminders {

  /**
   * Synchronise les rappels admin.
   * Appele par le cron quotidien via ReminderEngine.dailyCronJob().
   */
  static async syncAll(): Promise<void> {
    const now = new Date();
    const currentYear = now.getFullYear();

    // --- ANIL Data Update (October) ---
    const anilDueDate = new Date(`${currentYear}-10-15`);
    const anilReminderDate = new Date(`${currentYear}-10-01`);

    if (now < anilDueDate) {
      const existingAnil = await prisma.legalReminder.findFirst({
        where: {
          userId: null,
          type: LegalReminderType.ANIL_DATA_UPDATE,
          status: { notIn: ['COMPLETED', 'DISMISSED'] },
          dueDate: {
            gte: new Date(`${currentYear}-01-01`),
            lte: new Date(`${currentYear}-12-31`),
          },
        },
      });

      if (!existingAnil) {
        await prisma.legalReminder.create({
          data: {
            userId: null,
            type: LegalReminderType.ANIL_DATA_UPDATE,
            priority: LegalReminderPriority.HIGH,
            title: `Mise à jour données ANIL ${currentYear}`,
            description: `Vérifier si l'ANIL a publié les nouvelles données de loyers de marché. Télécharger le CSV et relancer le script d'import : npx tsx scripts/import-rent-data.ts <fichier.csv>`,
            actionUrl: 'https://www.data.gouv.fr/fr/datasets/carte-des-loyers-indicateurs-de-loyers-dannonce-par-commune/',
            dueDate: anilDueDate,
            reminderDate: anilReminderDate,
            isAutoGenerated: true,
            sourceField: 'ADMIN_CALENDAR',
            recurrenceRule: 'YEARLY',
          },
        });
      }
    }

    // --- Rent Control Data Update (July) ---
    const rcDueDate = new Date(`${currentYear}-07-15`);
    const rcReminderDate = new Date(`${currentYear}-07-01`);

    if (now < rcDueDate) {
      const existingRc = await prisma.legalReminder.findFirst({
        where: {
          userId: null,
          type: LegalReminderType.RENT_CONTROL_DATA_UPDATE,
          status: { notIn: ['COMPLETED', 'DISMISSED'] },
          dueDate: {
            gte: new Date(`${currentYear}-01-01`),
            lte: new Date(`${currentYear}-12-31`),
          },
        },
      });

      if (!existingRc) {
        await prisma.legalReminder.create({
          data: {
            userId: null,
            type: LegalReminderType.RENT_CONTROL_DATA_UPDATE,
            priority: LegalReminderPriority.HIGH,
            title: `Mise à jour encadrement des loyers ${currentYear}`,
            description: `Les nouveaux arrêtés d'encadrement des loyers entrent en vigueur au 1er juillet. Vérifier et mettre à jour les données dans lib/rentControl.ts pour toutes les zones couvertes.`,
            actionUrl: '/admin',
            dueDate: rcDueDate,
            reminderDate: rcReminderDate,
            isAutoGenerated: true,
            sourceField: 'ADMIN_CALENDAR',
            recurrenceRule: 'YEARLY',
          },
        });
      }
    }
  }
}
