import prisma from "@/libs/prismadb";
import { LegalReminderType, LegalReminderPriority } from "@prisma/client";

/**
 * Gere les rappels fiscaux pour les proprietaires.
 *
 * TAX_DECLARATION_DEADLINE :
 * - Chaque annee, rappel le 1er avril pour la declaration mi-mai
 * - Due date : 20 mai de l'annee en cours
 * - Cree pour tous les proprietaires ayant au moins un bien
 * - Recurrence : YEARLY
 */
export class TaxReminders {

  /**
   * Synchronise les rappels fiscaux pour tous les proprietaires.
   * Appele par le cron quotidien via ReminderEngine.dailyCronJob().
   */
  static async syncAll(): Promise<void> {
    const now = new Date();
    const currentYear = now.getFullYear();

    // Due date : 20 mai de l'annee en cours
    const dueDate = new Date(`${currentYear}-05-20`);

    // Ne creer les rappels que si on est avant la date limite
    if (now > dueDate) return;

    // Rappel : 1er avril
    const reminderDate = new Date(`${currentYear}-04-01`);
    // Second rappel : 1er mai
    const secondReminderDate = new Date(`${currentYear}-05-01`);

    // Trouver tous les proprietaires ayant au moins un bien
    const owners = await prisma.property.findMany({
      select: {
        ownerId: true
      },
      distinct: ['ownerId']
    });

    for (const { ownerId } of owners) {
      // Verifier si un rappel fiscal actif existe deja pour cette annee
      const existing = await prisma.legalReminder.findFirst({
        where: {
          userId: ownerId,
          type: LegalReminderType.TAX_DECLARATION_DEADLINE,
          status: { notIn: ['COMPLETED', 'DISMISSED'] },
          dueDate: {
            gte: new Date(`${currentYear}-01-01`),
            lte: new Date(`${currentYear}-12-31`)
          }
        }
      });

      if (!existing) {
        await prisma.legalReminder.create({
          data: {
            userId: ownerId,
            type: LegalReminderType.TAX_DECLARATION_DEADLINE,
            priority: LegalReminderPriority.HIGH,
            title: `Declaration de revenus fonciers ${currentYear}`,
            description: `Votre récap fiscal ${currentYear - 1} est disponible. Consultez-le pour préparer votre déclaration de revenus fonciers 2044. Date limite de déclaration en ligne : environ le 20 mai.`,
            legalReference: 'Art. 28 CGI — Declaration des revenus fonciers',
            actionUrl: '/account/fiscal',
            dueDate,
            reminderDate,
            secondReminderDate,
            isAutoGenerated: true,
            sourceField: 'TAX_CALENDAR',
            recurrenceRule: 'YEARLY'
          }
        });
      }
    }
  }
}
